import type { Metadata } from "next";
import {  Inter, JetBrains_Mono } from "next/font/google";
import "@/styles/globals.css";
import { AuthProvider } from "@/providers/auth-provider";

const InterFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  // all weights
});

const JetBrainsMono = JetBrains_Mono({
  variable: "--font-jet-brains_mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "AI Search & Chat",
  description: "Generated by create-assistant-ui",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${InterFont.className} ${JetBrainsMono.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
