import type { Metadata } from "next";
import {  Montserrat, Noto_Sans_Mono } from "next/font/google";
import "@/styles/globals.css";
import { AuthProvider } from "@/providers/auth-provider";

const MontserratFont = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  // all weights
});

const NotoSansMono = Noto_Sans_Mono({
  variable: "--font-noto-sans-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "AI Search & Chat",
  description: "Generated by create-assistant-ui",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${MontserratFont.className} ${NotoSansMono.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
