"""Add role and metadata to MessageModel

Revision ID: 4c7a32cae76a
Revises: 1b8f7744ee25
Create Date: 2025-05-05 23:05:58.274746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c7a32cae76a'
down_revision: Union[str, None] = '1b8f7744ee25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('role', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('message_metadata', sa.JSON(), nullable=True))
    op.drop_column('threads', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'message_metadata')
    op.drop_column('messages', 'role')
    # ### end Alembic commands ###
