"""Add message_id to MessageModel

Revision ID: b34eecb80f21
Revises: 4c7a32cae76a
Create Date: 2025-05-06 23:11:56.007523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b34eecb80f21'
down_revision: Union[str, None] = '4c7a32cae76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_column('messages', 'message_id')
    # ### end Alembic commands ###
