# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "ee746691b7206a415aaffd025e2dd9690cb934613525f61c7400817b6c8094e2"  # change this!
  limiter: false  # enable this when running the instance for a public usage on the internet
  image_proxy: true
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
search:
  formats:
    - html
    - json